### ISSUE TITLE
Property 'download' does not exist on type 'Transfer'.

### ISSUE THREAD

**Issue by AkashM08** [dsgriffin/ionic-3-file-transfer-example#10]
Facing below error message:

Property 'download' does not exist on type 'Transfer'. 

      L43:  		  fileTransfer.download(imageLocation, this.storageDirectory + image).then((entry) => {

[11:57:09]  typescript: src/pages/home/home.ts, line: 71 
            Property 'checkFile' does not exist on type 'typeof File'. 

      L71:      File.checkFile(this.storageDirectory, image)
      L72:        .then(() => {

Can you help me with this ?

**Comment by dsgriffin** [comment]
@AkashM08 You need to make sure you've installed [Transfer](http://ionicframework.com/docs/native/transfer/) and [File](http://ionicframework.com/docs/native/file/) via. the instructions in the links. Restart after that and it should sort your issue, otherwise follow the advice [in this answer](https://forum.ionicframework.com/t/ionic2-typescript-project-with-cordova-plugins/44090/29?u=dsgriffin), replacing the `cordova/plugins/statusbar` bit with relevant plugin(s)

**Comment by dsgriffin** [comment]
@AkashM08 Feel free to let me know if this resolved your issue. I've updated the project to use Ionic  3 now and was unable to replicate your issue, hope it's fixed!

**Comment by AkashM08** [comment]
@dsgriffin thank you. The issue was resolved. Thank you for your time.
